#web server
server:
    port: 8888
    contextPath: /oauth2service

#data source properties
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oauth2
    username: postgres
    password: admin

#Application specific
authentication:
  oauth:
    clientid: client
    secret: secret
    tokenValidityInSeconds: 1800